### PR TITLE
Use ulimits

### PR DESCRIPTION
**Pull request by jhudsy**
I have made a change that uses ulimit for time and memory limits. Defaults are specified in the config file, while a new limits.json file in each problem set can be used to set limits on a per-problem basis.

### CODE REVIEW

**Comment by theSage21** [comment]
You've tested locally?

**Comment by jhudsy** [comment]
I have, with a single testcase, namely the infinite loop to check that it gets terminated.

**Comment by theSage21** [comment]
That should be ok for now. I'll add some test cases on the current version and then merge this. Sound good?

**Comment by jhudsy** [comment]
just a second, I'm now testing some cases that should work, there seems to be a problem in the way I've defined the wrapper, looking at it now.

**Comment by jhudsy** [comment]
Right, I have tested a case that does work, and it passes. However, while a failing case now doesn't cause a process to keep running in the background, openjudge doesn't detect that it has timed out properly. I'm looking into it now. Oddly enough, I do get
" 139.133.205.39 - - [19/Oct/2017 14:40:48] "POST /user/leader HTTP/1.1" 200 41
False  Timeout ----------
Attempt qprmygfyglecdplfavntremgsrrqte status None" on the screen., but the status is stuck on "The attempt has been sent to the judge". This could be because I had broken things earlier, I'm about to try with a clean install of openjudge.

**Comment by jhudsy** [comment]
I've been digging into it. There seems to be a more general bug (in the original code) when a timeout occurs, as attempt_id is no longer in contest['attempts'] when this happens, the status stays on "The attempt has been sent to the judge". The fix is to keep the attempt_id in contest['attempts'] with a timeout status, but I'm still trying to work out where in the code this happens.

**Comment by theSage21** [comment]
I might be able to look at this codebase more closely after 5 Nov. I have
an exam coming up and after that I'm free. If you do manage to fix this a
PR is more than welcome.

**Comment by jhudsy** [comment]
Hi, ok, the code in the pull request (seems to) works fine, the problem is actually indeed a more general one when timeouts occur; I'll file an issue report for that one (and see if I can work out a good fix), but the ulimit code in this pull request can be integrated with the main codebase.

Good luck for your exam.

**Pull request merged**
